### ISSUE TITLE
Autocompletion not working

### ISSUE THREAD

**Issue by sebastianvera** [iamcco/coc-tailwindcss#24]
```
2020-04-15T01:20:16.748 ERROR (pid:51762) [completion-complete] - Complete error: tailwindCSS TypeError: Cannot read property 'newText' of undefined
    at Languages.convertVimCompleteItem (/Users/myuser/.config/nvim/plugged/coc.nvim/build/index.js:51844:58)
    at /Users/myuser/.config/nvim/plugged/coc.nvim/build/index.js:51629:37
    at Array.map (<anonymous>)
    at Object.doComplete (/Users/myuser/.config/nvim/plugged/coc.nvim/build/index.js:51628:43)
```

I just noticed that the autocompletion is not working, I updated tailwindcss version from `1.1.3` to `1.2.0` a few weeks ago but not sure if that's related. I'm new to coc so I'm not sure what else to do to give you more information, please let me know how I can help.

Here's my tailwindcss config if it helps: https://github.com/apipath/ppoker-graphql-react/blob/master/tailwind.config.js

Thanks for your awesome work!!

**Comment by iamcco** [comment]
coc's issue, update your coc
